name: Build and Test

on:
  pull_request:
    branches: [ main, feat/* ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Compile
      run: npm run compile
    - name: Run Unit Tests
      run: |
        npm run test
        npm run tests-devnet
